linters:
  enable:
    - gci

linters-settings:
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - blank # Blank section: contains all blank imports.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/pulumi/) # Custom section: groups all imports with the github.com/pulumi/ prefix.
      - prefix(github.com/pulumi/upgrade-provider) # Custom section: local imports
    custom-order: true
