package upgrade

import (
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/Masterminds/semver/v3"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/mod/module"

	"github.com/pulumi/upgrade-provider/step/v2"
)

func TestInspectLocalUpgrade(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	runGit := func(args ...string) {
		t.Helper()
		cmd := exec.Command("git", append([]string{"-C", dir}, args...)...)
		output, err := cmd.CombinedOutput()
		require.NoError(t, err, string(output))
	}

	runGit("init", "--initial-branch=main")
	runGit("config", "user.name", "Upgrade Provider Test")
	runGit("config", "user.email", "upgrade-provider@example.com")
	require.NoError(t, os.WriteFile(filepath.Join(dir, "result.txt"), []byte("base\n"), 0o600))
	runGit("add", "result.txt")
	runGit("commit", "-m", "base")
	// Model the remote base without requiring a real remote repository.
	runGit("update-ref", "refs/remotes/origin/main", "HEAD")
	require.NoError(t, os.WriteFile(filepath.Join(dir, "result.txt"), []byte("upgraded\n"), 0o600))
	runGit("add", "result.txt")
	runGit("commit", "-m", "upgrade")

	state := inspectLocalUpgrade(context.Background(), ProviderRepo{root: dir, defaultBranch: "main"})
	assert.Equal(t, "origin/main", state.BaseRef)
	assert.Equal(t, "clean", state.WorkingTree)
	assert.Equal(t, "1", state.CommitsAhead)

	require.NoError(t, os.WriteFile(filepath.Join(dir, "uncommitted.txt"), []byte("dirty\n"), 0o600))
	assert.Equal(t, "dirty",
		inspectLocalUpgrade(context.Background(), ProviderRepo{root: dir, defaultBranch: "main"}).WorkingTree)
}

func TestNoSubmitOutput(t *testing.T) {
	t.Parallel()

	body := "This PR was generated by upgrade-provider.\n\n---\n\n- Upgrade the provider.\n"
	output := noSubmitOutput(
		ProviderRepo{root: "/work/pulumi-example"},
		githubSubmissionPlan{
			Repository:               "pulumi/pulumi-example",
			BaseBranch:               "main",
			WorkingBranch:            "upgrade-example-to-v1.2.3",
			Title:                    "Upgrade terraform-provider-example to v1.2.3",
			Body:                     body,
			Label:                    "needs-release/patch",
			Reviewers:                "pulumi/Providers",
			Assignee:                 "@me",
			IssueAssignments:         []int{123},
			CloseSupersededBridgePRs: true,
			Targets:                  []string{"terraform-provider-example: 1.2.2 -> 1.2.3"},
		},
		localUpgradeState{
			BaseRef:      "origin/main",
			WorkingTree:  "clean",
			CommitsAhead: "2",
		},
	)

	// Check every report section without making the test brittle to harmless
	// whitespace changes between sections.
	for _, expected := range []string{
		"Upgrade completed locally; no branch was pushed and no PR was created or updated.",
		"Repository:            pulumi/pulumi-example",
		"Local path:            /work/pulumi-example",
		"Base branch:           main",
		"Working branch:        upgrade-example-to-v1.2.3",
		"Working tree:          clean",
		"Commits ahead:         2 (origin/main)",
		"- terraform-provider-example: 1.2.2 -> 1.2.3",
		"Title:                 Upgrade terraform-provider-example to v1.2.3",
		"Labels:                needs-release/patch",
		"Reviewers:             pulumi/Providers",
		"Assignee:              @me",
		"Issue assignments:     #123 -> @me",
		"Superseded bridge PRs: close open bridge upgrade PRs authored by @me, except this branch",
		"Body:\n" + body,
		"git log --oneline origin/main..HEAD",
		"git diff --stat origin/main...HEAD",
		"git diff origin/main...HEAD",
		"git push --set-upstream origin upgrade-example-to-v1.2.3 --force",
		"Assign the listed issues to the PR assignee.",
		"Close open bridge upgrade PRs authored by @me, except this branch, and comment with the replacement PR URL.",
	} {
		assert.Contains(t, output, expected)
	}
}

func TestGitHubSubmissionPlan(t *testing.T) {
	t.Parallel()

	ctx := (&Context{
		UpgradeProviderVersion: true,
		UpstreamProviderName:   "terraform-provider-example",
		PrReviewers:            "pulumi/Providers",
		PrAssign:               "@me",
	}).Wrap(context.Background())
	target := &UpstreamUpgradeTarget{
		Version:  semver.MustParse("1.2.3"),
		GHIssues: []UpgradeTargetIssue{{Number: 123}},
	}
	repo := ProviderRepo{
		Org:                    "pulumi",
		Name:                   "pulumi-example",
		defaultBranch:          "main",
		workingBranch:          "upgrade-example-to-v1.2.3",
		prTitle:                "Upgrade terraform-provider-example to v1.2.3",
		currentUpstreamVersion: semver.MustParse("1.2.2"),
	}

	// The plan should collect both PR metadata and post-creation issue work.
	plan := newGitHubSubmissionPlan(ctx, target, repo, &GoMod{}, nil, "",
		[]string{"upgrade-provider", "pulumi/pulumi-example", "--no-submit"})

	assert.Equal(t, "pulumi/pulumi-example", plan.Repository)
	assert.Equal(t, "needs-release/patch", plan.Label)
	assert.Equal(t, "pulumi/Providers", plan.Reviewers)
	assert.Equal(t, "@me", plan.Assignee)
	assert.Equal(t, []int{123}, plan.IssueAssignments)
	assert.Equal(t, []string{"terraform-provider-example: 1.2.2 -> 1.2.3"}, plan.Targets)
	assert.Contains(t, plan.Body, "Fixes #123")
}

func TestPRArgsIncludeAllMetadata(t *testing.T) {
	t.Parallel()

	plan := githubSubmissionPlan{
		BaseBranch:    "main",
		WorkingBranch: "upgrade-example",
		Title:         "Upgrade example",
		Body:          "PR body",
		Label:         "needs-release/patch",
		Reviewers:     "pulumi/Providers",
		Assignee:      "@me",
	}

	// A new PR must retain both assignee and label options; the old code lost the
	// assignee when a release label was selected.
	assert.Equal(t, []string{
		"pr", "create",
		"--base", "main",
		"--head", "upgrade-example",
		"--reviewer", "pulumi/Providers",
		"--title", "Upgrade example",
		"--body", "PR body",
		"--assignee", "@me",
		"--label", "needs-release/patch",
	}, createPRArgs(plan))
	// Existing PRs should receive the same configured metadata using gh's
	// additive edit flags.
	assert.Equal(t, []string{
		"pr", "edit", "upgrade-example",
		"--title", "Upgrade example",
		"--body", "PR body",
		"--add-reviewer", "pulumi/Providers",
		"--add-assignee", "@me",
		"--add-label", "needs-release/patch",
	}, editPRArgs(plan))
}

func TestInformGitHubNoSubmit(t *testing.T) {
	t.Parallel()

	repo := ProviderRepo{workingBranch: "upgrade-example-to-v1.2.3"}
	ctx := (&Context{NoSubmit: true}).Wrap(context.Background())
	recorder := &stepRecorder{}
	ctx = step.WithEnv(ctx, recorder)

	var prURL string
	err := step.PipelineCtx(ctx, "No submit", func(ctx context.Context) {
		prURL = InformGitHub(ctx, nil, repo, nil, nil, "", nil)
	}, step.NullDisplay)

	require.NoError(t, err)
	assert.Empty(t, prURL)
	assert.Equal(t, []string{"Inform Github"}, recorder.stepNames)
	assert.Equal(t,
		`Submission skipped: upgrade completed locally; branch "upgrade-example-to-v1.2.3" and its commits are ready for review. Use git push and gh to create or update the PR`,
		submissionSkippedMessage(repo.workingBranch))
}

func TestInformGithub(t *testing.T) {
	ctx := newReplay(t, "wavefront_inform_github")

	ctx = (&Context{
		UpgradeProviderVersion: true,
		PrAssign:               "@me",
		PrReviewers:            "pulumi/Providers,lukehoban",
		UpstreamProviderName:   "terraform-provider-wavefront",
		UpstreamProviderOrg:    "vmware",
	}).Wrap(ctx)

	err := step.PipelineCtx(ctx, "Tfgen & Build SDKs", func(ctx context.Context) {
		InformGitHub(ctx,
			&UpstreamUpgradeTarget{
				GHIssues: []UpgradeTargetIssue{
					{Number: 232},
				},
				Version: semver.MustParse("5.0.5"),
			}, ProviderRepo{
				workingBranch:          "upgrade-terraform-provider-wavefront-to-v5.0.5",
				prTitle:                "Upgrade terraform-provider-wavefront to v5.0.5",
				defaultBranch:          "master",
				Name:                   "pulumi/pulumi-wavefront",
				currentUpstreamVersion: semver.MustParse("5.0.3"),
			}, &GoMod{
				Kind: "plain",
				Upstream: module.Version{
					Path:    "github.com/vmware/terraform-provider-wavefront",
					Version: "v0.0.0-20231006183745-aa9a262f8bb0",
				},
				Bridge: module.Version{
					Path:    "github.com/pulumi/pulumi-terraform-bridge/v3",
					Version: "v3.61.0",
				},
			}, nil, "Up to date at 2.29.0", []string{"upgrade-provider", "pulumi/pulumi-wavefront"})
	})
	require.NoError(t, err)
}

func TestInformGithubExistingPR(t *testing.T) {
	ctx := newReplay(t, "kong_existing_pr")

	ctx = (&Context{
		PrAssign:             "@me",
		PrReviewers:          "pulumi/Providers,lukehoban",
		UpstreamProviderName: "terraform-provider-kong",
		UpstreamProviderOrg:  "kevholditch",
		UpgradeBridgeVersion: true,
	}).Wrap(ctx)

	err := step.PipelineCtx(ctx, "Tfgen & Build SDKs", func(ctx context.Context) {
		InformGitHub(ctx,
			nil, ProviderRepo{
				workingBranch:   "upgrade-pulumi-terraform-bridge-to-v3.62.0",
				prTitle:         "Upgrade pulumi-terraform-bridge to v3.62.0",
				defaultBranch:   "master",
				Org:             "pulumi",
				Name:            "pulumi-kong",
				prAlreadyExists: true,
			}, &GoMod{
				Kind: "plain",
				Upstream: module.Version{
					Path:    "github.com/kevholditch/terraform-provider-kong",
					Version: "v1.9.2-0.20220328204855-9e50bd93437f",
				},
				Bridge: module.Version{
					Path:    "github.com/pulumi/pulumi-terraform-bridge/v3",
					Version: "v3.60.0",
				},
			},
			&Version{SemVer: semver.MustParse("v3.62.0")},
			"Up to date at 2.29.0",
			[]string{
				"upgrade-provider",
				"pulumi/pulumi-kong", "--kind=bridge",
			})
	})
	require.NoError(t, err)
}

func TestBridgeUpgradeNoop(t *testing.T) {
	ctx := newReplay(t, "gcp_noop_bridge_update")
	ctx = (&Context{
		GoPath:               "/goPath",
		UpgradeBridgeVersion: true,
		TargetBridgeRef:      &Latest{},
		UpstreamProviderOrg:  "hashicorp",
	}).Wrap(ctx)

	err := step.CallWithReplay(ctx, "Plan Upgrade",
		"Planning Bridge Upgrade", planBridgeUpgrade)
	require.NoError(t, err)

	assert.False(t, GetContext(ctx).UpgradeBridgeVersion)
}

func TestApplyMajorVersionPolicy(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name        string
		current     string
		target      string
		major       bool
		allowMajor  bool
		unknown     bool
		expectMajor bool
		expectErr   string
	}{
		{
			name:        "minor upgrade without flags proceeds normally",
			current:     "1.1.0",
			target:      "1.2.0",
			expectMajor: false,
		},
		{
			name:        "minor upgrade with allow-major proceeds normally",
			current:     "1.1.0",
			target:      "1.2.0",
			allowMajor:  true,
			expectMajor: false,
		},
		{
			name:        "minor upgrade with major assertion errors",
			current:     "1.1.0",
			target:      "1.2.0",
			major:       true,
			expectMajor: true,
			expectErr:   "--major version update indicated, but no major upgrade available (already on v1)",
		},
		{
			name:        "major upgrade without flags errors",
			current:     "1.1.0",
			target:      "2.0.0",
			expectMajor: false,
			expectErr:   "this is a major version update (v1 -> v2), but neither --major nor --allow-major was passed",
		},
		{
			name:        "major upgrade with allow-major enables major bump",
			current:     "1.1.0",
			target:      "2.0.0",
			allowMajor:  true,
			expectMajor: true,
		},
		{
			name:        "major upgrade with major assertion proceeds",
			current:     "1.1.0",
			target:      "2.0.0",
			major:       true,
			expectMajor: true,
		},
		{
			name:        "major upgrade with both flags proceeds",
			current:     "1.1.0",
			target:      "2.0.0",
			major:       true,
			allowMajor:  true,
			expectMajor: true,
		},
		{
			name:      "unknown current upstream version errors",
			target:    "2.0.0",
			unknown:   true,
			expectErr: "could not determine current upstream version; cannot determine whether 2.0.0 is a major version update",
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			c := &Context{
				UpgradeProviderVersion: true,
				MajorVersionBump:       tt.major,
				AllowMajorVersionBump:  tt.allowMajor,
			}
			ctx := c.Wrap(context.Background())
			repo := ProviderRepo{}
			if !tt.unknown {
				repo.currentUpstreamVersion = semver.MustParse(tt.current)
			}
			target := &UpstreamUpgradeTarget{
				Version: semver.MustParse(tt.target),
			}

			err := applyMajorVersionPolicy(ctx, &repo, target)
			if tt.expectErr != "" {
				require.EqualError(t, err, tt.expectErr)
			} else {
				require.NoError(t, err)
			}
			assert.Equal(t, tt.expectMajor, c.MajorVersionBump)
		})
	}
}

func newReplay(t *testing.T, name string) context.Context {
	t.Helper()
	ctx := context.Background()
	path := filepath.Join("testdata", "replay", name+".json")
	bytes := readFile(t, path)
	r := step.NewReplay(t, bytes)
	return step.WithEnv(ctx, r)
}

func readFile(t *testing.T, path string) []byte {
	t.Helper()
	bytes, err := os.ReadFile(path)
	require.NoError(t, err)
	return bytes
}

func testReplay(ctx context.Context, t *testing.T, stepReplay []*step.Step, fName string, f any) {
	t.Helper()
	bytes, err := json.Marshal(step.ReplayV1{
		Pipelines: []step.RecordV1{{
			Name:  t.Name(),
			Steps: stepReplay,
		}},
	})
	require.NoError(t, err)

	r := step.NewReplay(t, bytes)
	ctx = step.WithEnv(ctx, r)

	err = step.CallWithReplay(ctx, t.Name(), fName, f)
	assert.NoError(t, err)
}

// stepRecorder verifies that the no-submit guard returns before any nested git
// or gh command steps are entered.
type stepRecorder struct {
	stepNames []string
}

func (r *stepRecorder) Enter(_ context.Context, info step.StepInfo) error {
	r.stepNames = append(r.stepNames, info.Name())
	return nil
}

func (*stepRecorder) Exit(context.Context, []any) error { return nil }
func (*stepRecorder) String() string                    { return "recording step names" }

func jsonMarshal[T any](t *testing.T, content string) T {
	t.Helper()
	var dst T
	err := json.Unmarshal([]byte(content), &dst)
	require.NoError(t, err)
	return dst
}
