env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GOLANGCI_LINT_VERSION: v2.13.2
name: Pull Request
on: [pull_request]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@master
      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Download module dependencies
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go mod download
      - name: Build
        run: make build
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          install-only: true
      - name: Lint
        run: make lint
      - name: Test
        run: make test
